# Generated by Django 3.0.8 on 2021-09-28 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('idRol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=150)),
                ('correo', models.CharField(max_length=100)),
                ('idRol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestorComidas.Rol')),
            ],
        ),
        migrations.CreateModel(
            name='Recordatorio',
            fields=[
                ('idRecord', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('idUsuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestorComidas.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Preferencias',
            fields=[
                ('idPrefer', models.AutoField(primary_key=True, serialize=False)),
                ('preferencia', models.CharField(max_length=200)),
                ('personaliza', models.CharField(max_length=200)),
                ('fecha', models.CharField(max_length=200)),
                ('idUsuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestorComidas.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('idMenu', models.AutoField(primary_key=True, serialize=False)),
                ('menu', models.CharField(max_length=200)),
                ('fecha', models.CharField(max_length=200)),
                ('idUsuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestorComidas.Usuario')),
            ],
        ),
    ]
